# Introduction

Google Trends gives us an estimate of search volume. Let's explore if search popularity relates to other kinds of data. Perhaps there are patterns in Google's search volume and the price of Bitcoin or a hot stock like Tesla. Perhaps search volume for the term "Unemployment Benefits" can tell us something about the actual unemployment rate? 

Data Sources: <br>
<ul>
<li> <a href="https://fred.stlouisfed.org/series/UNRATE/">Unemployment Rate from FRED</a></li>
<li> <a href="https://trends.google.com/trends/explore">Google Trends</a> </li>  
<li> <a href="https://finance.yahoo.com/quote/TSLA/history?p=TSLA">Yahoo Finance for Tesla Stock Price</a> </li>    
<li> <a href="https://finance.yahoo.com/quote/BTC-USD/history?p=BTC-USD">Yahoo Finance for Bitcoin Stock Price</a> </li>
</ul>

## Import Statements

In [280]:
# import matplotlib.pyplot as plt
import pandas as pd

## Read the Data

Download and add the .csv files to the same folder as your notebook.

In [281]:
df_tesla = pd.read_csv('data/TESLA Search Trend vs Price.csv')

df_btc_search = pd.read_csv('data/Bitcoin Search Trend.csv')
df_btc_price = pd.read_csv('data/Daily Bitcoin Price.csv')

df_unemployment_19 = pd.read_csv('data/UE Benefits Search vs UE Rate 2004-19.csv')
df_unemployment_20 = pd.read_csv('data/UE Benefits Search vs UE Rate 2004-20.csv')

## Data Exploration

### Tesla

**Challenge**: <br>
<ul>
<li>What are the shapes of the dataframes? </li>
<li>How many rows and columns? </li>
<li>What are the column names? </li>
<li>Complete the f-string to show the largest/smallest number in the search data column</li> 
<li>Try the <code>.describe()</code> function to see some useful descriptive statistics</li>
<li>What is the periodicity of the time series data (daily, weekly, monthly)? </li>
<li>What does a value of 100 in the Google Trend search popularity actually mean?</li>
</ul>

#### Tesla DF Shape

In [282]:
print(f"Tesla DF has {df_tesla.shape[0]} rows and {df_tesla.shape[1]} rows")

Tesla DF has 124 rows and 3 rows

#### Tesla DF Head

In [283]:
df_tesla.head()

        MONTH  TSLA_WEB_SEARCH  TSLA_USD_CLOSE
0  2010-06-01                3           4.766
1  2010-07-01                3           3.988
2  2010-08-01                2           3.896
3  2010-09-01                2           4.082
4  2010-10-01                2           4.368

#### Tesla Columns name

In [284]:
print("Tesla has the following columns:")
for column in df_tesla.columns:
    print(column)

Tesla has the following columns:
MONTH
TSLA_WEB_SEARCH
TSLA_USD_CLOSE

#### Tesla Web Search Largest and Smallest value

In [285]:
tsla__web_search_max = df_tesla['TSLA_WEB_SEARCH'].max()
tsla__web_search_min = df_tesla['TSLA_WEB_SEARCH'].min()

print(f'Largest value for Tesla in Web Search: {tsla__web_search_max}')
print(f'Smallest value for Tesla in Web Search: {tsla__web_search_min}')

Largest value for Tesla in Web Search: 31
Smallest value for Tesla in Web Search: 2

#### Tesla DF describe

In [286]:
df_tesla.describe()

       TSLA_WEB_SEARCH  TSLA_USD_CLOSE
count       124.000000      124.000000
mean          8.725806       50.962145
std           5.870332       65.908389
min           2.000000        3.896000
25%           3.750000        7.352500
50%           8.000000       44.653000
75%          12.000000       58.991999
max          31.000000      498.320007

#### Periodicity of data

In [287]:
# Convert MONTH column to datetime
df_tesla['MONTH'] = pd.to_datetime(df_tesla['MONTH'])
df_tesla.MONTH.dtypes

dtype('<M8[us]')

In [288]:
df_tesla.MONTH.diff()

0         NaT
1     30 days
2     31 days
3     31 days
4     30 days
        ...
119   30 days
120   31 days
121   30 days
122   31 days
123   31 days
Name: MONTH, Length: 124, dtype: timedelta64[us]

In [289]:
periodicity = pd.infer_freq(df_tesla['MONTH'])
if periodicity == 'MS':
    print('Periodicity is Monthly, at the Month start')

Periodicity is Monthly, at the Month start

### Unemployment Data

#### UE Data Shape

In [290]:
df_unemployment_19.shape

(181, 3)

In [291]:
df_unemployment_20.shape

(200, 3)

#### UE Data Head

In [292]:
df_unemployment_19.head()

     MONTH  UE_BENEFITS_WEB_SEARCH  UNRATE
0  2004-01                      34     5.7
1  2004-02                      33     5.6
2  2004-03                      25     5.8
3  2004-04                      29     5.6
4  2004-05                      23     5.6

In [293]:
df_unemployment_20.head()

     MONTH  UE_BENEFITS_WEB_SEARCH  UNRATE
0  2004-01                       9     5.7
1  2004-02                       8     5.6
2  2004-03                       7     5.8
3  2004-04                       8     5.6
4  2004-05                       6     5.6

#### UE Columns

In [294]:
df_unemployment_19.columns

Index(['MONTH', 'UE_BENEFITS_WEB_SEARCH', 'UNRATE'], dtype='str')

#### UE Largest and Smallest

In [295]:
ue_largest_19 = df_unemployment_19['UE_BENEFITS_WEB_SEARCH'].max()
ue_smallest_19 = df_unemployment_19['UE_BENEFITS_WEB_SEARCH'].min()
ue_largest_20 = df_unemployment_20['UE_BENEFITS_WEB_SEARCH'].max()
ue_smallest_20 = df_unemployment_20['UE_BENEFITS_WEB_SEARCH'].min()

In [296]:
print('Largest value for "Unemployemnt Benefits" '
      f'in Web Search: {ue_largest_20}')

Largest value for "Unemployemnt Benefits" in Web Search: 100

#### UE Describe

In [297]:
df_unemployment_19.describe()

       UE_BENEFITS_WEB_SEARCH      UNRATE
count              181.000000  181.000000
mean                35.110497    6.217680
std                 20.484925    1.891859
min                 14.000000    3.700000
25%                 21.000000    4.700000
50%                 26.000000    5.400000
75%                 45.000000    7.800000
max                100.000000   10.000000

In [298]:
df_unemployment_20.describe()

       UE_BENEFITS_WEB_SEARCH      UNRATE
count              200.000000  200.000000
mean                10.315000    6.173000
std                 10.778061    2.128267
min                  4.000000    3.500000
25%                  5.000000    4.600000
50%                  7.000000    5.400000
75%                 12.000000    7.825000
max                100.000000   14.700000

#### Periodicity of data

In [299]:
# Convert MONTH column to datetime
df_unemployment_20['MONTH'] = pd.to_datetime(df_unemployment_19['MONTH'])
df_unemployment_20.MONTH.dtypes

dtype('<M8[us]')

In [300]:
df_unemployment_20.MONTH.diff()

0         NaT
1     31 days
2     29 days
3     31 days
4     30 days
        ...
195       NaT
196       NaT
197       NaT
198       NaT
199       NaT
Name: MONTH, Length: 200, dtype: timedelta64[us]

In [301]:
df_unemployment_20[df_unemployment_20['MONTH'].notna()]

         MONTH  UE_BENEFITS_WEB_SEARCH  UNRATE
0   2004-01-01                       9     5.7
1   2004-02-01                       8     5.6
2   2004-03-01                       7     5.8
3   2004-04-01                       8     5.6
4   2004-05-01                       6     5.6
..         ...                     ...     ...
176 2018-09-01                       4     3.7
177 2018-10-01                       4     3.8
178 2018-11-01                       4     3.7
179 2018-12-01                       5     3.9
180 2019-01-01                       6     4.0

[181 rows x 3 columns]

In [302]:
periodicity = pd.infer_freq(df_unemployment_20['MONTH'][df_unemployment_20['MONTH'].notna()])
if periodicity == 'MS':
    print('Periodicity is Monthly, at the Month start')
else:
    print(periodicity)

Periodicity is Monthly, at the Month start

### Bitcoin

#### Bitcoin Data Shape

In [303]:
df_btc_price.shape

(2204, 3)

In [304]:
df_btc_search.shape

(73, 2)

#### Bitcoin Data Head

In [305]:
df_btc_price.head()

         DATE       CLOSE      VOLUME
0  2014-09-17  457.334015  21056800.0
1  2014-09-18  424.440002  34483200.0
2  2014-09-19  394.795990  37919700.0
3  2014-09-20  408.903992  36863600.0
4  2014-09-21  398.821014  26580100.0

In [306]:
df_btc_search.head()

     MONTH  BTC_NEWS_SEARCH
0  2014-09                5
1  2014-10                4
2  2014-11                4
3  2014-12                4
4  2015-01                5

#### Bitcoin Columns

In [307]:
df_btc_price.columns

Index(['DATE', 'CLOSE', 'VOLUME'], dtype='str')

In [308]:
df_btc_search.columns

Index(['MONTH', 'BTC_NEWS_SEARCH'], dtype='str')

#### Bitcoin Largest and Smallest

In [309]:
BTC_largest_search = df_btc_search['BTC_NEWS_SEARCH'].max()
BTC_smallest_search = df_btc_search['BTC_NEWS_SEARCH'].min()

In [310]:
print(f'Largest BTC News Search in Web Search: {BTC_largest_search}')

Largest BTC News Search in Web Search: 100

#### Bitcoin Describe

In [311]:
df_unemployment_19.describe()

       UE_BENEFITS_WEB_SEARCH      UNRATE
count              181.000000  181.000000
mean                35.110497    6.217680
std                 20.484925    1.891859
min                 14.000000    3.700000
25%                 21.000000    4.700000
50%                 26.000000    5.400000
75%                 45.000000    7.800000
max                100.000000   10.000000

In [312]:
df_unemployment_20.describe()

                            MONTH  UE_BENEFITS_WEB_SEARCH      UNRATE
count                         181              200.000000  200.000000
mean   2011-07-02 01:51:22.872928               10.315000    6.173000
min           2004-01-01 00:00:00                4.000000    3.500000
25%           2007-10-01 00:00:00                5.000000    4.600000
50%           2011-07-01 00:00:00                7.000000    5.400000
75%           2015-04-01 00:00:00               12.000000    7.825000
max           2019-01-01 00:00:00              100.000000   14.700000
std                           NaN               10.778061    2.128267

#### Periodicity of data

In [313]:
# Convert MONTH column to datetime
df_unemployment_20['MONTH'] = pd.to_datetime(df_unemployment_19['MONTH'])
df_unemployment_20.MONTH.dtypes

dtype('<M8[us]')

In [314]:
df_unemployment_20.MONTH.diff()

0         NaT
1     31 days
2     29 days
3     31 days
4     30 days
        ...
195       NaT
196       NaT
197       NaT
198       NaT
199       NaT
Name: MONTH, Length: 200, dtype: timedelta64[us]

In [315]:
df_unemployment_20[df_unemployment_20['MONTH'].notna()]

         MONTH  UE_BENEFITS_WEB_SEARCH  UNRATE
0   2004-01-01                       9     5.7
1   2004-02-01                       8     5.6
2   2004-03-01                       7     5.8
3   2004-04-01                       8     5.6
4   2004-05-01                       6     5.6
..         ...                     ...     ...
176 2018-09-01                       4     3.7
177 2018-10-01                       4     3.8
178 2018-11-01                       4     3.7
179 2018-12-01                       5     3.9
180 2019-01-01                       6     4.0

[181 rows x 3 columns]

In [316]:
periodicity = pd.infer_freq(df_unemployment_20['MONTH'][df_unemployment_20['MONTH'].notna()])
if periodicity == 'MS':
    print('Periodicity is Monthly, at the Month start')
else:
    print(periodicity)

Periodicity is Monthly, at the Month start

# Data Cleaning

### Check for Missing Values

**Challenge**: Are there any missing values in any of the dataframes? If so, which row/rows have missing values? How many missing values are there?

In [317]:
# Telsa missing values
df_tesla_isna = df_tesla.isna().values.any()
df_unemployment_isna = df_unemployment_19.isna().values.any()
df_bitcoin_isna = df_btc_search.isna().values.any()
df_bitcoin_isna.item()

False

In [318]:
print(f'Missing values for Tesla?: {df_tesla_isna}')
print(f'Missing values for U/E?: {df_unemployment_isna}')
print(f'Missing values for BTC Search?: {df_bitcoin_isna}')

Missing values for Tesla?: False
Missing values for U/E?: False
Missing values for BTC Search?: False

In [319]:
df_bitcoin_price_isna = df_btc_price.isna().any().any() # .any().any() is a good alternative to .values.any()
df_bitcoin_price_isna.item()

True

In [320]:
print(f'Missing values for BTC price?: {df_bitcoin_price_isna}')

Missing values for BTC price?: True

In [321]:
print(f'Number of missing values: {df_btc_price.isna().sum().sum()}')
df_btc_price[df_btc_price.CLOSE.isna()]

Number of missing values: 2

            DATE  CLOSE  VOLUME
2148  2020-08-04    NaN     NaN

**Challenge**: Remove any missing values that you found.

In [322]:
df_btc_price.dropna(inplace=True) # Drop the not available values and the update the dataframe
df_btc_price[df_btc_price.CLOSE.isna()]

Empty DataFrame
Columns: [DATE, CLOSE, VOLUME]
Index: []

### Convert Strings to DateTime Objects

**Challenge**: Check the data type of the entries in the DataFrame MONTH or DATE columns. Convert any strings in to Datetime objects. Do this for all 4 DataFrames. Double check if your type conversion was successful.

#### Tesla check and convert datetime

In [323]:
df_tesla.dtypes
# Looks like columns MONTH is correctly set as datetime.

MONTH              datetime64[us]
TSLA_WEB_SEARCH             int64
TSLA_USD_CLOSE            float64
dtype: object

#### Bitcoin check and convert datetime

In [324]:
df_btc_price.dtypes
# Date is string: it needs to be converted

DATE          str
CLOSE     float64
VOLUME    float64
dtype: object

In [325]:
df_btc_price["DATE"] = pd.to_datetime(df_btc_price["DATE"])
df_btc_price.dtypes
# Converted successfully

DATE      datetime64[us]
CLOSE            float64
VOLUME           float64
dtype: object

In [326]:
df_btc_search.dtypes

MONTH                str
BTC_NEWS_SEARCH    int64
dtype: object

In [327]:
df_btc_search["MONTH"] = pd.to_datetime(df_btc_search["MONTH"])
df_btc_search.dtypes

MONTH              datetime64[us]
BTC_NEWS_SEARCH             int64
dtype: object

#### Unemployment check and convert datetime

In [328]:
df_unemployment_19.dtypes

MONTH                         str
UE_BENEFITS_WEB_SEARCH      int64
UNRATE                    float64
dtype: object

In [329]:
df_unemployment_19["MONTH"] = pd.to_datetime(df_unemployment_19["MONTH"])
df_unemployment_19.dtypes

MONTH                     datetime64[us]
UE_BENEFITS_WEB_SEARCH             int64
UNRATE                           float64
dtype: object

In [331]:
df_unemployment_20.dtypes
# Looks all good

MONTH                     datetime64[us]
UE_BENEFITS_WEB_SEARCH             int64
UNRATE                           float64
dtype: object

### Converting from Daily to Monthly Data

[Pandas .resample() documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) <br>

In [337]:
df_btc_monthly_price = df_btc_price.resample("ME", on="DATE").mean()
print(df_btc_monthly_price.shape)
df_btc_monthly_price.head()

(73, 2)

                 CLOSE        VOLUME
DATE
2014-09-30  407.182428  2.934864e+07
2014-10-31  364.148873  2.912885e+07
2014-11-30  366.099799  2.199111e+07
2014-12-31  341.267871  1.784201e+07
2015-01-31  248.782547  3.544555e+07

In [338]:
df_btc_monthly_price = df_btc_price.resample("ME", on="DATE").last()
print(df_btc_monthly_price.shape)
df_btc_monthly_price.head()

(73, 2)

                 CLOSE      VOLUME
DATE
2014-09-30  386.944000  34707300.0
2014-10-31  338.321014  12545400.0
2014-11-30  378.046997   9194440.0
2014-12-31  320.192993  13942900.0
2015-01-31  217.464005  23348200.0

# Data Visualisation

### Notebook Formatting & Style Helpers

In [274]:
# Create locators for ticks on the time axis

In [275]:
# Register date converters to avoid warning messages

### Tesla Stock Price v.s. Search Volume

**Challenge:** Plot the Tesla stock price against the Tesla search volume using a line chart and two different axes. Label one axis 'TSLA Stock Price' and the other 'Search Trend'.

**Challenge**: Add colours to style the chart. This will help differentiate the two lines and the axis labels. Try using one of the blue [colour names](https://matplotlib.org/3.1.1/gallery/color/named_colors.html) for the search volume and a HEX code for a red colour for the stock price. 
<br>
<br>
Hint: you can colour both the [axis labels](https://matplotlib.org/3.3.2/api/text_api.html#matplotlib.text.Text) and the [lines](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) on the chart using keyword arguments (kwargs).

**Challenge**: Make the chart larger and easier to read. 
1. Increase the figure size (e.g., to 14 by 8). 
2. Increase the font sizes for the labels and the ticks on the x-axis to 14. 
3. Rotate the text on the x-axis by 45 degrees. 
4. Make the lines on the chart thicker. 
5. Add a title that reads 'Tesla Web Search vs Price'
6. Keep the chart looking sharp by changing the dots-per-inch or [DPI value](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.figure.html). 
7. Set minimum and maximum values for the y and x axis. Hint: check out methods like [set_xlim()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_xlim.html). 
8. Finally use [plt.show()](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.show.html) to display the chart below the cell instead of relying on the automatic notebook output.

How to add tick formatting for dates on the x-axis.

### Bitcoin (BTC) Price v.s. Search Volume

**Challenge**: Create the same chart for the Bitcoin Prices vs. Search volumes. <br>
1. Modify the chart title to read 'Bitcoin News Search vs Resampled Price' <br>
2. Change the y-axis label to 'BTC Price' <br>
3. Change the y- and x-axis limits to improve the appearance <br>
4. Investigate the [linestyles](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.plot.html ) to make the BTC price a dashed line <br>
5. Investigate the [marker types](https://matplotlib.org/3.2.1/api/markers_api.html) to make the search datapoints little circles <br>
6. Were big increases in searches for Bitcoin accompanied by big increases in the price?

### Unemployement Benefits Search vs. Actual Unemployment in the U.S.

**Challenge** Plot the search for "unemployment benefits" against the unemployment rate. 
1. Change the title to: Monthly Search of "Unemployment Benefits" in the U.S. vs the U/E Rate <br>
2. Change the y-axis label to: FRED U/E Rate <br>
3. Change the axis limits <br>
4. Add a grey [grid](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.grid.html) to the chart to better see the years and the U/E rate values. Use dashes for the line style<br> 
5. Can you discern any seasonality in the searches? Is there a pattern?

**Challenge**: Calculate the 3-month or 6-month rolling average for the web searches. Plot the 6-month rolling average search data against the actual unemployment. What do you see in the chart? Which line moves first?

### Including 2020 in Unemployment Charts

**Challenge**: Read the data in the 'UE Benefits Search vs UE Rate 2004-20.csv' into a DataFrame. Convert the MONTH column to Pandas Datetime objects and then plot the chart. What do you see?