# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

## About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

## Import Statements

In [599]:
import pandas as pd
import plotly.express as px

## Notebook Presentation

In [600]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

## Read the Dataset

In [601]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

### Check rows and columsn of `df_apps`

In [602]:
rows, columns = df_apps.shape
print(f"df_apps has {rows} rows and {columns} columns")

df_apps has 10841 rows and 12 columns

### Check the columns

In [603]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [604]:
# df_apps.dtypes returns a Series where:
#   Series index  = DataFrame column names
#   Series values = each column's dtype
#
# Passing the Series directly to pd.DataFrame() would create one vertical column.
# Wrapping it in [...] changes the input to a "list containing one Series".
# DataFrame interprets each Series inside that list as one ROW, so the Series'
# index labels become the new DataFrame's column names.
#
# index=["dtype"] then names that single generated row "dtype".
# Finally, concat() stacks that dtype row above the first real data row.
pd.concat([
    pd.DataFrame([df_apps.dtypes.astype(str)], index=["dtype"]),
    df_apps.head(1)
])

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
dtype,str,str,float64,int64,float64,str,str,str,str,str,str,str
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up

In [605]:
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
1497,PlayMotiv dn edition,BUSINESS,NaN,0,28.00,500,Free,0,Everyone,Business,"April 8, 2018",4.1 and up
5207,Hot Bhojpuri Video Song 2018 - Free Movies,FAMILY,4.40,447,3.70,"100,000",Free,0,Mature 17+,Entertainment,"April 4, 2018",4.2 and up
10684,Talking Tom Gold Run,GAME,4.60,2698889,78.00,"100,000,000",Free,0,Everyone,Action,"July 31, 2018",4.1 and up
8130,AirWatch Agent,BUSINESS,3.10,20973,31.00,"5,000,000",Free,0,Everyone,Business,"August 1, 2018",4.0 and up
1632,EG Retail,BUSINESS,2.40,29,16.00,500,Free,0,Everyone,Business,"July 5, 2018",4.1 and up

In [606]:
df_apps.describe()

        Rating       Reviews  Size_MBs
count 9,367.00     10,841.00 10,841.00
mean      4.19    444,111.93     19.77
std       0.52  2,927,628.66     21.40
min       1.00          0.00      0.01
25%       4.00         38.00      4.90
50%       4.30      2,094.00     11.00
75%       4.50     54,768.00     27.00
max       5.00 78,158,306.00    100.00

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [607]:
# Drop the two columns
df_apps.drop(["Last_Updated", "Android_Ver"], axis="columns", inplace=True)
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres'],
      dtype='str')

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [608]:
df_apps.Rating.isna().sum()

np.int64(1474)

In [609]:
df_apps.isna().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size_MBs             0
Installs             0
Type                 1
Price                0
Content_Rating       0
Genres               0
dtype: int64

In [610]:
pd.DataFrame(
    [df_apps.isna().sum()],
    index=["NaN_count"]
)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
NaN_count,0,0,1474,0,0,0,1,0,0,0

In [611]:
# df_apps_clean = df_apps[df_apps.Rating.isna() == False]
# df_apps_clean = df_apps[df_apps.Rating.notna()]
# df_apps_clean = df_apps.dropna(subset=["Rating"])
df_apps_clean = df_apps.dropna()
df_apps_clean

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [612]:
print(f" There are {df_apps_clean.duplicated().sum()} duplicates")

 There are 476 duplicates

In [613]:
df_apps_clean

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

In [614]:
df_apps_clean[df_apps_clean["App"] == "Instagram"]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [615]:
# Angela Challenge: does Instagram have duplicates?
df_apps_clean[df_apps_clean["App"] == "Instagram"].duplicated()

10806    False
10808    False
10809     True
10810    False
dtype: bool

In [616]:
# Angela Challenge: how many duplicates has "Instagram"?
df_apps_clean[df_apps_clean["App"] == "Instagram"].duplicated().sum()

np.int64(1)

In [617]:
# With all the columns included in the check, it is too strict, and rarely is possible to find duplicates
df_apps_clean = df_apps_clean.drop_duplicates(subset=["App", "Type", "Price"])
df_apps_clean

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10824,Google Drive,PRODUCTIVITY,4.40,2731171,4.00,"1,000,000,000",Free,0,Everyone,Productivity
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10829,Google Play Movies & TV,VIDEO_PLAYERS,3.70,906384,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10831,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,"1,000,000,000",Free,0,Teen,News & Magazines
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

In [618]:
print(f"There are zero {df_apps_clean.duplicated().sum()} duplicates")

There are zero 0 duplicates

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [619]:
# Review counts help understand if the Rating comes from a high number of people
df_apps_clean[df_apps_clean.Rating == df_apps_clean.Rating.max()].sort_values("Reviews", ascending=False).head(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2095,Ríos de Fe,LIFESTYLE,5.00,141,15.00,"1,000",Free,0,Everyone,Lifestyle
2438,"FD Calculator (EMI, SIP, RD & Loan Eligilibility)",FINANCE,5.00,104,2.30,"1,000",Free,0,Everyone,Finance
3115,Oración CX,LIFESTYLE,5.00,103,3.80,"5,000",Free,0,Everyone,Lifestyle
2107,Barisal University App-BU Face,FAMILY,5.00,100,10.00,"1,000",Free,0,Everyone,Education
2069,Master E.K,FAMILY,5.00,90,19.00,"1,000",Free,0,Everyone,Education

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [620]:
df_apps_clean[df_apps_clean.Size_MBs == df_apps_clean.Size_MBs.max()]["App"].count()

np.int64(14)

In [621]:
# 100MB appears to be the max size of an app.
df_apps_clean[df_apps_clean.Size_MBs == df_apps_clean.Size_MBs.max()].sort_values("Size_MBs", ascending=False).head(14)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
1795,Navi Radiography Pro,MEDICAL,4.70,11,100.00,500,Paid,$15.99,Everyone,Medical
3144,Vi Trainer,HEALTH_AND_FITNESS,3.60,124,100.00,"5,000",Free,0,Everyone,Health & Fitness
4176,Car Crash III Beam DH Real Damage Simulator 2018,GAME,3.60,151,100.00,"10,000",Free,0,Everyone,Racing
7926,Post Bank,FINANCE,4.50,60449,100.00,"1,000,000",Free,0,Everyone,Finance
7927,The Walking Dead: Our World,GAME,4.00,22435,100.00,"1,000,000",Free,0,Teen,Action
7928,Stickman Legends: Shadow Wars,GAME,4.40,38419,100.00,"1,000,000",Paid,$0.99,Everyone 10+,Action
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports
8719,Draft Simulator for FUT 18,SPORTS,4.60,162933,100.00,"5,000,000",Free,0,Everyone,Sports
9942,Talking Babsy Baby: Baby Games,LIFESTYLE,4.00,140995,100.00,"10,000,000",Free,0,Everyone,Lifestyle;Pretend Play
9943,Miami crime simulator,GAME,4.00,254518,100.00,"10,000,000",Free,0,Mature 17+,Action
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
10295,SimCity BuildIt,FAMILY,4.50,4218587,100.00,"50,000,000",Free,0,Everyone 10+,Simulation
10687,Hungry Shark Evolution,GAME,4.50,6074334,100.00,"100,000,000",Free,0,Teen,Arcade

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [622]:
# First it is created a DataFrame with top 50 apps, and on that the counts shows the not free apps among them
top50 = df_apps_clean.sort_values("Reviews", ascending=False).head(50)
top50.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy

In [623]:
# top50_count = top50[top50.Type != "Free"]["App"].count()
# print(f"There are {top50_count} paid apps among top 50")
top50_count = top50["Type"].value_counts()
for app_type, count in top50_count.items():
    print(f"{app_type}: {count} apps")

Free: 50 apps

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [624]:
ratings = df_apps_clean.Content_Rating.value_counts()
for index, value in ratings.items():
    print(f"{index}: {value}")

Everyone: 6621
Teen: 912
Mature 17+: 357
Everyone 10+: 305
Adults only 18+: 3
Unrated: 1

In [625]:
fig = px.pie(
    labels=ratings.index,
    values=ratings.values,
    title="Content Rating",
    names=ratings.index,
    hole=0.6
)

fig.update_traces(
    textposition='outside',
    textinfo='percent+label'
)

fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [626]:
# Understand the type of string present as values
df_apps_clean["Installs"].value_counts()

Installs
1,000,000        1417
100,000          1096
10,000            988
10,000,000        933
1,000             698
5,000,000         607
500,000           504
50,000            457
5,000             425
100               303
50,000,000        202
500               199
100,000,000       189
10                 69
50                 56
500,000,000        24
1,000,000,000      20
5                   9
1                   3
Name: count, dtype: int64

In [627]:
# Replace the elements that make invalid int
df_apps_clean["Installs"] = df_apps_clean["Installs"].str.replace(",","")

In [628]:
# Convert into integer
df_apps_clean["Installs"] = df_apps_clean.Installs.astype("int64")
df_apps_clean.Installs.dtypes

dtype('int64')

In [629]:
# Install_counts = df_apps_clean.sort_values("Installs", ascending=False)
Install_counts = df_apps_clean["Installs"].value_counts().sort_index(ascending=False)
Install_counts

Installs
1000000000      20
500000000       24
100000000      189
50000000       202
10000000       933
5000000        607
1000000       1417
500000         504
100000        1096
50000          457
10000          988
5000           425
1000           698
500            199
100            303
50              56
10              69
5                9
1                3
Name: count, dtype: int64

In [630]:
# for index, count in Install_counts.items():
#     total_count = df_apps_clean[df_apps_clean["Installs"] >= index]["App"].count()
#     print(f"Installs {index}: {total_count}")

In [631]:
# Count the apps that has above 1,000,000 installs
Install_counts.loc[1_000_000_000]

np.int64(20)

In [632]:
# Count the apps that has 1 single install
Install_counts.loc[1]

np.int64(3)

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [633]:
# Understand the type of string present as values
df_apps_clean.Price.describe()

count     8199
unique      73
top          0
freq      7595
Name: Price, dtype: object

In [634]:
# Understand the type of string present as values
df_apps_clean.info()

<class 'pandas.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   str
 1   Category        8199 non-null   str
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   int64
 6   Type            8199 non-null   str
 7   Price           8199 non-null   str
 8   Content_Rating  8199 non-null   str
 9   Genres          8199 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 704.6 KB

In [635]:
df_apps_clean.groupby("Price")["App"].count()

Price
$0.99     104
$1.00       2
$1.20       1
$1.29       1
$1.49      31
         ...
$8.49       1
$8.99       4
$9.00       1
$9.99      14
0        7595
Name: App, Length: 73, dtype: int64

In [636]:
# Replace the elements that make invalid int
df_apps_clean["Price"] = df_apps_clean["Price"].str.replace("$","")
df_apps_clean.Price.head()

21       0
28    1.49
47    0.99
82       0
99       0
Name: Price, dtype: str

In [637]:
# Converto to numeric
df_apps_clean["Price"] = pd.to_numeric(df_apps_clean["Price"])

df_apps_clean.groupby("Price")["App"].count()

Price
0.00      7595
0.99       104
1.00         2
1.20         1
1.29         1
          ...
299.99       1
379.99       1
389.99       1
399.99      11
400.00       1
Name: App, Length: 73, dtype: int64

### The most expensive apps sub $250

In [638]:
df_apps_sub250 = df_apps_clean[df_apps_clean["Price"] < 250]
df_apps_sub250.sort_values("Price", ascending=False).head(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
2463,PTA Content Master,MEDICAL,4.20,64,41.00,1000,Paid,29.99,Everyone,Medical
2207,EMT PASS,MEDICAL,3.40,51,2.40,1000,Paid,29.99,Everyone,Medical
4264,Golfshot Plus: Golf GPS,SPORTS,4.10,3387,25.00,50000,Paid,29.99,Everyone,Sports
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education
4772,Human Anatomy Atlas 2018: Complete 3D Human Body,MEDICAL,4.50,2921,25.00,100000,Paid,24.99,Everyone,Medical
3241,"Muscle Premium - Human Anatomy, Kinesiology, B...",MEDICAL,4.20,168,25.00,10000,Paid,24.99,Everyone,Medical

### Highest Grossing Paid Apps (ballpark estimate)

In [639]:
df_apps_sub250["Revenue_estimate"] = df_apps_sub250.Installs.mul(df_apps_sub250.Price)
df_apps_sub250_top10 = df_apps_sub250[["App", "Category", "Installs", "Price", "Revenue_estimate"]].sort_values("Revenue_estimate", ascending=False).head(10)

df_apps_sub250_top10

,App,Category,Installs,Price,Revenue_estimate
9220,Minecraft,FAMILY,10000000,6.99,"69,900,000.00"
8825,Hitman Sniper,GAME,10000000,0.99,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,1000000,6.99,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,1000000,5.99,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,1000000,5.99,"5,990,000.00"
6594,DraStic DS Emulator,GAME,1000000,4.99,"4,990,000.00"
6082,Weather Live,WEATHER,500000,5.99,"2,995,000.00"
7954,Bloons TD 5,FAMILY,1000000,2.99,"2,990,000.00"
7633,Five Nights at Freddy's,GAME,1000000,2.99,"2,990,000.00"
6746,Card Wars - Adventure Time,FAMILY,1000000,2.99,"2,990,000.00"

In [640]:
df_apps_sub250_top10.groupby("Category")["App"].count()

Category
FAMILY         3
GAME           4
LIFESTYLE      1
PHOTOGRAPHY    1
WEATHER        1
Name: App, dtype: int64

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

### Vertical Bar Chart - Highest Competition (Number of Apps)

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

# Grouped Bar Charts: Free vs. Paid Apps per Category

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.